services:
  migrate:
    environment:
      APP_ENCRYPTION_KEY: ""
      APP_ENCRYPTION_KEY_FILE: /run/secrets/app_encryption_key
    secrets:
      - app_encryption_key

  web:
    environment:
      APP_ENCRYPTION_KEY: ""
      APP_ENCRYPTION_KEY_FILE: /run/secrets/app_encryption_key
    secrets:
      - app_encryption_key

  worker:
    environment:
      APP_ENCRYPTION_KEY: ""
      APP_ENCRYPTION_KEY_FILE: /run/secrets/app_encryption_key
    secrets:
      - app_encryption_key

secrets:
  app_encryption_key:
    file: ./secrets/app_encryption_key
